<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="QuoteTemplateGenerator\**\*.cs" />
    <EmbeddedResource Remove="QuoteTemplateGenerator\**\*" />
    <None Remove="QuoteTemplateGenerator\**\*" />

    <Compile Remove="IdGenerationInspector\**\*.cs" />
    <EmbeddedResource Remove="IdGenerationInspector\**\*" />
    <None Remove="IdGenerationInspector\**\*" />

    <Compile Remove="IdReservationDryRun\**\*.cs" />
    <EmbeddedResource Remove="IdReservationDryRun\**\*" />
    <None Remove="IdReservationDryRun\**\*" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.2.2" />
  </ItemGroup>

</Project>
